/**
 * ============================================================================
 * ACT 1 FACT PROMPT SCREEN - Private Fact Gathering
 * ============================================================================
 *
 * This screen shows a private fact-gathering prompt generated by the LLM.
 * The active player answers privately, then the answer is stored in the facts DB.
 *
 * Flow:
 * 1. Fetch LLM-generated prompt (on mount)
 * 2. Show cover screen (privacy protection)
 * 3. Player holds to reveal prompt
 * 4. Player enters answer in textarea
 * 5. Submit → store fact → transition to confirm screen
 *
 * Design requirements:
 * - Full viewport (no scroll)
 * - Hold-to-reveal privacy cover
 * - Loading state while fetching prompt
 * - Error handling for LLM failures
 */

'use client';

import { useState, useEffect } from 'react';
import { GameState, Player, LLMResponse, EventLog, FactsDB } from '@/types/game';
import { requestFactPrompt, LLMError } from '@/lib/llmClient';
import { INPUT_MODULES } from '@/lib/constants';

/**
 * Props for Act1FactPromptScreen
 */
interface Act1FactPromptScreenProps {
  /** Current game state */
  state: GameState;

  /** All players */
  players: Player[];

  /** Event log (for LLM context) */
  eventLog: EventLog;

  /** Facts DB (for LLM context) */
  factsDB: FactsDB;

  /** Current scores */
  scores: Record<string, number>;

  /** Safety mode */
  safetyMode: 'kid-safe' | 'teen-adult';

  /** Callback when answer is submitted */
  onSubmit: (answer: string, llmResponse: LLMResponse) => void;

  /** Callback to cancel/go back */
  onCancel?: () => void;
}

/**
 * Act 1 Fact Prompt Screen Component
 */
export function Act1FactPromptScreen({
  state,
  players,
  eventLog,
  scores,
  safetyMode,
  onSubmit,
  onCancel,
}: Act1FactPromptScreenProps) {
  // ===========================================================================
  // STATE
  // ===========================================================================

  const [isLoading, setIsLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);
  const [llmResponse, setLlmResponse] = useState<LLMResponse | null>(null);
  const [answer, setAnswer] = useState('');
  const [isRevealed, setIsRevealed] = useState(false);
  const [holdProgress, setHoldProgress] = useState(0);

  // ===========================================================================
  // FETCH LLM PROMPT
  // ===========================================================================

  useEffect(() => {
    async function fetchPrompt() {
      try {
        setIsLoading(true);
        setError(null);

        const response = await requestFactPrompt(
          state,
          eventLog,
          players,
          scores,
          safetyMode
        );

        setLlmResponse(response);
      } catch (err: any) {
        console.error('Failed to fetch fact prompt:', err);

        if (err instanceof LLMError) {
          setError(err.message);
        } else {
          setError('Failed to generate prompt. Please try again.');
        }
      } finally {
        setIsLoading(false);
      }
    }

    fetchPrompt();
  }, [state.sessionId]); // Only fetch once on mount

  // ===========================================================================
  // ACTIVE PLAYER
  // ===========================================================================

  const activePlayer = players.find((p) => p.id === state.activePlayerId);

  if (!activePlayer) {
    return (
      <div className="viewport-container flex-center bg-danger-50">
        <div className="card text-center">
          <h1 className="text-xl font-bold text-danger-600 mb-2">Error</h1>
          <p className="text-neutral-600">No active player found</p>
        </div>
      </div>
    );
  }

  // ===========================================================================
  // LOADING STATE
  // ===========================================================================

  if (isLoading) {
    return (
      <div className="viewport-container flex-center bg-primary-50">
        <div className="text-center">
          <div className="spinner mb-4" />
          <p className="text-primary-700 font-semibold">
            Generating question for {activePlayer.name}...
          </p>
        </div>
      </div>
    );
  }

  // ===========================================================================
  // ERROR STATE
  // ===========================================================================

  if (error || !llmResponse) {
    return (
      <div className="viewport-container flex-center bg-danger-50 p-6">
        <div className="card max-w-2xl text-center">
          <h1 className="text-xl font-bold text-danger-600 mb-4">
            Oops! Something went wrong
          </h1>
          <p className="text-neutral-700 mb-2 font-semibold">Error Details:</p>
          <p className="text-neutral-600 mb-6 text-sm font-mono bg-neutral-100 p-3 rounded">
            {error || 'Unknown error - failed to generate question'}
          </p>
          <div className="text-left mb-6 text-sm text-neutral-600">
            <p className="font-semibold mb-2">Common causes:</p>
            <ul className="list-disc list-inside space-y-1">
              <li>OpenAI API key not set or invalid</li>
              <li>Network connection issues</li>
              <li>OpenAI service temporarily unavailable</li>
            </ul>
          </div>
          <div className="flex gap-2">
            {onCancel && (
              <button onClick={onCancel} className="btn-outline flex-1">
                Go Back
              </button>
            )}
            <button
              onClick={() => window.location.reload()}
              className="btn-primary flex-1"
            >
              Retry
            </button>
          </div>
        </div>
      </div>
    );
  }

  // ===========================================================================
  // HANDLE SUBMIT
  // ===========================================================================

  const handleSubmit = () => {
    if (!answer.trim()) return;

    onSubmit(answer.trim(), llmResponse);
  };

  // ===========================================================================
  // HOLD-TO-REVEAL HANDLERS
  // ===========================================================================

  const handlePressStart = () => {
    if (isRevealed) return;

    const startTime = Date.now();
    const interval = setInterval(() => {
      const elapsed = Date.now() - startTime;
      const progress = Math.min(elapsed / 1000, 1); // 1 second
      setHoldProgress(progress);

      if (progress >= 1) {
        setIsRevealed(true);
        clearInterval(interval);
      }
    }, 16); // 60fps

    // Store interval ID for cleanup
    (window as any).__holdInterval = interval;
  };

  const handlePressEnd = () => {
    if ((window as any).__holdInterval) {
      clearInterval((window as any).__holdInterval);
      delete (window as any).__holdInterval;
    }

    if (!isRevealed) {
      setHoldProgress(0);
    }
  };

  // ===========================================================================
  // RENDER
  // ===========================================================================

  const charLimit = INPUT_MODULES.TEXTAREA.MAX_LENGTH;
  const charCount = answer.length;
  const charPercent = (charCount / charLimit) * 100;
  const isNearLimit = charPercent >= 90;

  return (
    <div className="viewport-container bg-primary-50">
      {/* Status strip */}
      <div className="flex items-center justify-between px-6 py-4 bg-white border-b border-neutral-200">
        <div className="text-sm">
          <span className="font-semibold text-primary-600">Act 1</span>
          <span className="text-neutral-400 mx-2">•</span>
          <span className="text-neutral-600">Fact Gathering</span>
        </div>
        <div className="text-xl font-bold text-primary-600">
          {activePlayer.name}
        </div>
      </div>

      {/* Main content */}
      <div className="flex-1 flex flex-col p-6 overflow-hidden">
        {!isRevealed ? (
          /* Cover screen */
          <div className="flex-1 flex flex-col items-center justify-center">
            <div className="card max-w-2xl text-center">
              <div className="text-6xl mb-4">🚫</div>
              <h2 className="text-3xl font-bold mb-4">Private Question</h2>
              <p className="text-lg text-neutral-600 mb-2">
                Only
              </p>
              <p className="text-mega text-chunky text-primary-600 mb-6">
                {activePlayer.name}
              </p>
              <p className="text-base text-neutral-600 mb-6">
                should see this.
              </p>

              <button
                onMouseDown={handlePressStart}
                onMouseUp={handlePressEnd}
                onMouseLeave={handlePressEnd}
                onTouchStart={handlePressStart}
                onTouchEnd={handlePressEnd}
                className="btn-primary w-full relative overflow-hidden"
              >
                <span className="relative z-10">
                  {holdProgress === 0 ? 'Hold to Reveal' : 'Keep Holding...'}
                </span>
                {holdProgress > 0 && (
                  <div
                    className="absolute inset-0 bg-primary-700 transition-all"
                    style={{ width: `${holdProgress * 100}%` }}
                  />
                )}
              </button>

              <p className="text-sm text-neutral-500 mt-4">
                Hold for 1 second to see your question
              </p>
            </div>
          </div>
        ) : (
          /* Revealed content */
          <div className="flex-1 flex flex-col max-w-2xl mx-auto w-full">
            {/* Prompt */}
            <div className="mb-6">
              <h2 className="text-2xl font-bold mb-3">{llmResponse.screen.title}</h2>
              <p className="text-lg text-neutral-700 leading-relaxed">
                {llmResponse.screen.body}
              </p>
              <p className="text-sm text-neutral-500 mt-2">
                {llmResponse.screen.instructions}
              </p>
            </div>

            {/* Input */}
            <div className="flex-1 flex flex-col">
              <textarea
                value={answer}
                onChange={(e) => setAnswer(e.target.value)}
                placeholder="Type your answer here..."
                className="textarea flex-1 min-h-[120px]"
                maxLength={charLimit}
                autoFocus
              />

              {/* Character count */}
              <div className="flex justify-between items-center mt-2">
                <p className="text-sm text-neutral-500">
                  {charCount} / {charLimit} characters
                </p>
                {isNearLimit && (
                  <p className="text-sm text-warning-600 font-semibold">
                    Almost at limit!
                  </p>
                )}
              </div>
            </div>
          </div>
        )}
      </div>

      {/* Action bar */}
      {isRevealed && (
        <div className="px-6 py-4 bg-white border-t border-neutral-200">
          <button
            onClick={handleSubmit}
            disabled={!answer.trim()}
            className={`w-full ${
              answer.trim() ? 'btn-primary' : 'btn-outline opacity-50 cursor-not-allowed'
            }`}
          >
            Submit Answer
          </button>
        </div>
      )}
    </div>
  );
}
